name: rodney_flutter_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  collection: ^1.17.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
